# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=20)),
                ('score', models.IntegerField(null=True)),
                ('user', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('birth', models.IntegerField()),
                ('picture', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
    ]
