# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamline91', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
