# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamline91', '0002_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='HContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('bold', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('start', models.IntegerField(primary_key=True, serialize=False)),
                ('finish', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('bold', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Hobby',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
