# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamline91', '0003_auto_20180108_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='no',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personal',
            name='bold',
            field=models.CharField(max_length=50),
        ),
    ]
