# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamline91', '0004_auto_20180110_0001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HContent',
        ),
        migrations.AddField(
            model_name='history',
            name='etc',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='history',
            name='sub',
            field=models.IntegerField(default=0),
        ),
    ]
