# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamline91', '0005_auto_20180111_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='etc',
        ),
    ]
