# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamline91', '0008_happy'),
    ]

    operations = [
        migrations.AddField(
            model_name='happy',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
