# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamline91', '0009_happy_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='happy',
            name='content',
            field=models.TextField(),
        ),
    ]
