# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamline91', '0010_auto_20180122_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('bold', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
        ),
    ]
